[package]
name = "preprocess"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[dependencies]
libs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
memmap2 = { workspace = true }
rkyv = { workspace = true, features = ["alloc", "bytecheck", "validation"] }

[features]
default = []
testing-mode = ["libs/testing-mode"]
