[package]
name = "trusted-setup"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[dependencies]
bincode = { workspace = true }
icicle-core = { workspace = true }
icicle-bls12-381 = { workspace = true }
libs = { workspace = true }

[features]
default = []
testing-mode = ["libs/testing-mode"]
