[package]
name = "msm_test"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "msm_test"
path = "libs.rs"

[dependencies]
icicle-runtime = { workspace = true }
icicle-core = { workspace = true }
icicle-bls12-381 = { workspace = true }
icicle-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
byteorder = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
rayon = { workspace = true }
criterion = "0.3"
hex = "0.4.3"
ark-bls12-381 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
rand = { workspace = true }

[features]
default = []
testing-mode = []