[package]
name = "prove"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
icicle-runtime = { workspace = true }
icicle-core = { workspace = true }
icicle-bls12-381 = { workspace = true }
libs = { workspace = true }
tiny-keccak = "1.5"
# Note: Rayon cannot be used with ICICLE types as they don't implement Send/Sync

[dev-dependencies]
criterion = "0.5"
rand = { workspace = true }
tikv-jemallocator = "0.4"

[lib]
name = "prove"
path = "src/lib.rs"

[[bench]]
name = "batch_msm_simple"
harness = false

[[bench]]
name = "prove0_msm_batch"
harness = false

[[bench]]
name = "prove0_msm_async"
harness = false

[[bench]]
name = "prove_init_bench"
harness = false

[[bench]]
name = "prove4_bench"
harness = false

[[bench]]
name = "msm_sparse25"
path = "benches/msm_sparsity/sparse25.rs"
harness = false

[[bench]]
name = "msm_sparse50"
path = "benches/msm_sparsity/sparse50.rs"
harness = false

[[bench]]
name = "msm_sparse75"
path = "benches/msm_sparsity/sparse75.rs"
harness = false

[[bench]]
name = "msm_random"
path = "benches/msm_sparsity/random.rs"
harness = false

[features]
default = []
testing-mode = []
